# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    region  = "us-east-1"
    bucket  = "ksultan-terraform-backend"
    encrypt = true
    key     = "frontend-app/terraform.tfstate"
  }
}
